name: Test action
on: [push, pull_request]

jobs:
  clamd_macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Start ClamAV daemon
        uses: ./
        with:
          db_daily: true
      - name: Ping clamd on TCP port 3310
        run: echo PING | nc localhost 3310
      - name: Ping clamd using the Unix socket
        run: echo PING | nc -U /tmp/clamd.socket
  clamd_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Start ClamAV daemon
        uses: ./
        with:
          db_daily: true
      - name: Ping clamd on TCP port 3310
        run: echo PING | nc localhost 3310
      - name: Ping clamd using the Unix socket
        run: echo PING | nc -U /tmp/clamd.socket
  clamd_windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Start ClamAV daemon
        uses: ./
      - name: Test the connection to clamd on TCP port 3310
        run: Test-NetConnection -ComputerName localhost -Port 3310
